import { Document, Image, Page, Text, View } from "@react-pdf/renderer";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { getRiskLevel, getRiskLevelLabel } from "@/lib/scan-history/utils";
import { buildFinalRecommendations } from "@/lib/pdf-report/recommendations";
import { sanitizePdfText } from "@/lib/pdf-report/sanitize";
import { getSeverityPdfStyle, pdfColors, pdfStyles } from "@/lib/pdf-report/styles";
import { formatDuration, formatReportDate, getDifficultyLabel } from "@/lib/scan-report/utils";
import type { ScanReport, ScanReportFinding } from "@/lib/scan-report/types";

interface ScanReportPdfDocumentProps {
  report: ScanReport;
}

function getLogoSrc(): string | null {
  const logoPath = path.join(process.cwd(), "public", "scanonix_icon.png");
  if (!existsSync(logoPath)) return null;

  try {
    const buffer = readFileSync(logoPath);
    return `data:image/png;base64,${buffer.toString("base64")}`;
  } catch {
    return null;
  }
}

function ReportHeader({ reportId }: { reportId: string }) {
  const logoSrc = getLogoSrc();
  const generatedAt = new Intl.DateTimeFormat("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date());

  return (
    <View style={pdfStyles.header} fixed>
      <View style={pdfStyles.headerBrand}>
        {/* eslint-disable-next-line jsx-a11y/alt-text -- PDF renderer Image has no alt prop */}
        {logoSrc ? <Image src={logoSrc} style={pdfStyles.headerLogo} /> : null}
        <Text style={pdfStyles.headerBrandText}>SCANONIX</Text>
      </View>
      <View>
        <Text style={pdfStyles.headerMeta}>Security Scan Report</Text>
        <Text style={pdfStyles.headerMeta}>Report ID: {sanitizePdfText(reportId, 64)}</Text>
        <Text style={pdfStyles.headerMeta}>Generated: {generatedAt}</Text>
      </View>
    </View>
  );
}

function ReportFooter({ reportId }: { reportId: string }) {
  return (
    <View style={pdfStyles.footer} fixed>
      <Text style={pdfStyles.footerText}>Scanonix · {sanitizePdfText(reportId, 64)}</Text>
      <Text
        style={pdfStyles.footerText}
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
      <Text style={pdfStyles.footerText}>Generated by Scanonix</Text>
    </View>
  );
}

function DetailRow({ label, value }: { label: string; value: string }) {
  return (
    <View style={pdfStyles.row}>
      <Text style={pdfStyles.label}>{label}</Text>
      <Text style={pdfStyles.value}>{value}</Text>
    </View>
  );
}

function FindingSection({ finding }: { finding: ScanReportFinding }) {
  const severityStyle = getSeverityPdfStyle(finding.severity);

  return (
    <View style={pdfStyles.findingCard} wrap={false}>
      <View style={{ flexDirection: "row", justifyContent: "space-between", marginBottom: 6 }}>
        <Text style={pdfStyles.findingTitle}>{sanitizePdfText(finding.title, 200)}</Text>
        <Text style={[pdfStyles.badge, severityStyle]}>{finding.severity.toUpperCase()}</Text>
      </View>

      <Text style={pdfStyles.findingBody}>{sanitizePdfText(finding.description)}</Text>
      <Text style={pdfStyles.findingBody}>
        <Text style={{ fontFamily: "Helvetica-Bold" }}>Affected: </Text>
        {sanitizePdfText(finding.affectedFile)}
      </Text>
      <Text style={pdfStyles.findingBody}>
        <Text style={{ fontFamily: "Helvetica-Bold" }}>Why it matters: </Text>
        {sanitizePdfText(finding.whyItMatters)}
      </Text>
      <Text style={pdfStyles.findingBody}>
        <Text style={{ fontFamily: "Helvetica-Bold" }}>Recommended fix: </Text>
        {sanitizePdfText(finding.recommendation)}
      </Text>
      <Text style={pdfStyles.findingBody}>
        <Text style={{ fontFamily: "Helvetica-Bold" }}>Fix difficulty: </Text>
        {getDifficultyLabel(finding.fixDifficulty)}
      </Text>

      {finding.ai ? (
        <View style={{ marginTop: 6 }}>
          <Text style={pdfStyles.findingBody}>
            <Text style={{ fontFamily: "Helvetica-Bold" }}>Priority: </Text>
            {finding.ai.priority.toUpperCase()}
          </Text>
          <Text style={pdfStyles.findingBody}>
            <Text style={{ fontFamily: "Helvetica-Bold" }}>Business impact: </Text>
            {sanitizePdfText(finding.ai.businessImpact)}
          </Text>
          <Text style={pdfStyles.findingBody}>
            <Text style={{ fontFamily: "Helvetica-Bold" }}>Technical impact: </Text>
            {sanitizePdfText(finding.ai.technicalImpact)}
          </Text>
          <Text style={pdfStyles.findingBody}>
            <Text style={{ fontFamily: "Helvetica-Bold" }}>Estimated risk reduction: </Text>
            {finding.ai.estimatedRiskReduction}%
          </Text>
          <Text style={pdfStyles.findingBody}>
            <Text style={{ fontFamily: "Helvetica-Bold" }}>Confidence: </Text>
            {sanitizePdfText(finding.ai.confidenceExplanation)}
          </Text>
          {finding.ai.remediationSteps.map((step, index) => (
            <Text key={`${finding.id}-step-${index}`} style={pdfStyles.findingBody}>
              <Text style={{ fontFamily: "Helvetica-Bold" }}>Step {index + 1}: </Text>
              {sanitizePdfText(step)}
            </Text>
          ))}
        </View>
      ) : null}
    </View>
  );
}

export function ScanReportPdfDocument({ report }: ScanReportPdfDocumentProps) {
  const riskLevel = getRiskLevelLabel(getRiskLevel(report.riskScore));
  const recommendations = buildFinalRecommendations(report);
  const hasActionableFindings = report.findings.some((finding) => finding.severity !== "info");

  return (
    <Document
      title={`Scanonix Security Report — ${sanitizePdfText(report.target, 120)}`}
      author="Scanonix"
      subject="Security Scan Report"
    >
      <Page size="A4" style={pdfStyles.page} wrap>
        <ReportHeader reportId={report.id} />
        <ReportFooter reportId={report.id} />

        <Text style={pdfStyles.title}>Security Scan Report</Text>
        <Text style={pdfStyles.subtitle}>
          Professional security assessment for {sanitizePdfText(report.target, 200)}
        </Text>

        <View style={pdfStyles.card}>
          <DetailRow label="Report ID" value={sanitizePdfText(report.id, 64)} />
          <DetailRow label="Target" value={sanitizePdfText(report.target)} />
          <DetailRow
            label="Scan type"
            value={report.targetType === "website" ? "Website scan" : "File scan"}
          />
          <DetailRow label="Completed" value={formatReportDate(report.completedAt)} />
          <DetailRow label="Duration" value={formatDuration(report.durationMs)} />
        </View>

        <Text style={pdfStyles.sectionTitle}>Risk overview</Text>
        <View style={pdfStyles.metricsRow}>
          <View style={pdfStyles.metricBox}>
            <Text style={pdfStyles.metricLabel}>Risk score</Text>
            <Text style={[pdfStyles.metricValue, { color: pdfColors.orange }]}>
              {report.riskScore}/100
            </Text>
          </View>
          <View style={pdfStyles.metricBox}>
            <Text style={pdfStyles.metricLabel}>Risk level</Text>
            <Text style={pdfStyles.metricValue}>{riskLevel}</Text>
          </View>
          <View style={pdfStyles.metricBox}>
            <Text style={pdfStyles.metricLabel}>Critical issues</Text>
            <Text style={pdfStyles.metricValue}>{report.summary.criticalIssues}</Text>
          </View>
          <View style={pdfStyles.metricBox}>
            <Text style={pdfStyles.metricLabel}>Warnings</Text>
            <Text style={pdfStyles.metricValue}>{report.summary.warnings}</Text>
          </View>
        </View>

        <View style={pdfStyles.metricsRow}>
          <View style={pdfStyles.metricBox}>
            <Text style={pdfStyles.metricLabel}>Passed checks</Text>
            <Text style={pdfStyles.metricValue}>{report.summary.passedChecks}</Text>
          </View>
          <View style={pdfStyles.metricBox}>
            <Text style={pdfStyles.metricLabel}>AI confidence</Text>
            <Text style={pdfStyles.metricValue}>{report.summary.aiConfidence}%</Text>
          </View>
        </View>

        {report.intelligence?.domainReputation ? (
          <>
            <Text style={pdfStyles.sectionTitle}>Domain reputation</Text>
            <View style={pdfStyles.card}>
              <DetailRow label="Domain" value={sanitizePdfText(report.intelligence.domainReputation.domain)} />
              <DetailRow
                label="Reputation score"
                value={`${report.intelligence.domainReputation.reputationScore}/100`}
              />
              <DetailRow
                label="Trust level"
                value={sanitizePdfText(report.intelligence.domainReputation.trustLevel)}
              />
              <DetailRow
                label="Registrar"
                value={sanitizePdfText(report.intelligence.domainReputation.registration.registrar ?? "Unknown")}
              />
              <DetailRow
                label="Domain age"
                value={
                  report.intelligence.domainReputation.registration.ageDays !== null
                    ? `${report.intelligence.domainReputation.registration.ageDays} days`
                    : "Unknown"
                }
              />
              <DetailRow
                label="DNS health"
                value={sanitizePdfText(report.intelligence.domainReputation.dnsHealth.level)}
              />
              <DetailRow
                label="SPF"
                value={report.intelligence.domainReputation.dnsHealth.hasSpf ? "Detected" : "Missing"}
              />
              <DetailRow
                label="DMARC"
                value={report.intelligence.domainReputation.dnsHealth.hasDmarc ? "Detected" : "Missing"}
              />
              <DetailRow
                label="Hosting"
                value={sanitizePdfText(
                  report.intelligence.domainReputation.infrastructure.hostingProvider ?? "Unknown",
                )}
              />
              <Text style={pdfStyles.findingBody}>
                {sanitizePdfText(report.intelligence.domainReputation.summary)}
              </Text>
              {report.intelligence.domainReputation.riskReasons.map((reason) => (
                <Text key={reason} style={pdfStyles.bulletItem}>
                  • {sanitizePdfText(reason)}
                </Text>
              ))}
            </View>
          </>
        ) : null}

        {report.fileIntelligence ? (
          <>
            <Text style={pdfStyles.sectionTitle}>File intelligence</Text>
            <View style={pdfStyles.card}>
              <DetailRow label="Filename" value={sanitizePdfText(report.fileIntelligence.fileName)} />
              <DetailRow label="Extension" value={sanitizePdfText(report.fileIntelligence.extension || "none")} />
              <DetailRow label="Detected MIME" value={sanitizePdfText(report.fileIntelligence.detectedMimeType)} />
              <DetailRow label="Size" value={`${report.fileIntelligence.sizeBytes} bytes`} />
              <DetailRow label="Risk score" value={`${report.fileIntelligence.riskScore}/100`} />
              <DetailRow label="SHA256" value={sanitizePdfText(report.fileIntelligence.sha256, 80)} />
              <DetailRow label="MD5" value={sanitizePdfText(report.fileIntelligence.md5, 48)} />
              <Text style={pdfStyles.findingBody}>{sanitizePdfText(report.fileIntelligence.summary)}</Text>
              {report.fileIntelligence.recommendations.map((item) => (
                <Text key={item} style={pdfStyles.bulletItem}>
                  • {sanitizePdfText(item)}
                </Text>
              ))}
            </View>
          </>
        ) : null}

        <Text style={pdfStyles.sectionTitle}>Files analysed</Text>
        <View style={pdfStyles.card}>
          <DetailRow label="Scanned" value={String(report.files.scanned)} />
          <DetailRow label="Suspicious" value={String(report.files.suspicious)} />
          <DetailRow label="Safe" value={String(report.files.safe)} />
          <DetailRow label="Ignored" value={String(report.files.ignored)} />
        </View>

        <Text style={pdfStyles.sectionTitle}>Scan timeline</Text>
        <View style={pdfStyles.card}>
          {report.timeline.map((stage) => (
            <View key={stage.id} style={pdfStyles.timelineItem}>
              <View
                style={[
                  pdfStyles.timelineDot,
                  {
                    backgroundColor: stage.completed ? pdfColors.orange : pdfColors.grey200,
                  },
                ]}
              />
              <Text style={pdfStyles.timelineLabel}>
                {sanitizePdfText(stage.label, 80)}
                {stage.completed ? " · Complete" : " · Pending"}
              </Text>
            </View>
          ))}
        </View>

        <Text style={pdfStyles.sectionTitle}>Findings</Text>
        {!hasActionableFindings ? (
          <View style={pdfStyles.card}>
            <Text style={pdfStyles.findingBody}>
              No security issues were detected. The target passed static security checks with a low
              risk score.
            </Text>
          </View>
        ) : (
          report.findings.map((finding) => (
            <FindingSection key={finding.id} finding={finding} />
          ))
        )}

        {report.aiAnalysis ? (
          <>
            <Text style={pdfStyles.sectionTitle}>AI analysis summary</Text>
            <View style={pdfStyles.card}>
              <Text style={pdfStyles.findingBody}>
                <Text style={{ fontFamily: "Helvetica-Bold" }}>Executive summary: </Text>
                {sanitizePdfText(report.aiAnalysis.executiveSummary)}
              </Text>
              <Text style={pdfStyles.findingBody}>
                <Text style={{ fontFamily: "Helvetica-Bold" }}>Technical summary: </Text>
                {sanitizePdfText(report.aiAnalysis.technicalSummary)}
              </Text>
              <Text style={pdfStyles.findingBody}>
                <Text style={{ fontFamily: "Helvetica-Bold" }}>Security posture: </Text>
                {sanitizePdfText(report.aiAnalysis.overallSecurityPosture)}
              </Text>
              {report.aiAnalysis.topPriorities.map((item) => (
                <Text key={item} style={pdfStyles.bulletItem}>
                  • Priority: {sanitizePdfText(item)}
                </Text>
              ))}
            </View>
          </>
        ) : null}

        <Text style={pdfStyles.sectionTitle}>Final recommendations</Text>
        <View style={pdfStyles.card}>
          {recommendations.map((item) => (
            <Text key={item} style={pdfStyles.bulletItem}>
              • {sanitizePdfText(item)}
            </Text>
          ))}
        </View>

        <Text style={{ fontSize: 8, color: pdfColors.grey600, marginTop: 8 }}>
          Report generated on{" "}
          {new Intl.DateTimeFormat("en-GB", {
            dateStyle: "full",
            timeStyle: "short",
          }).format(new Date())}
        </Text>
      </Page>
    </Document>
  );
}
