"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { ScanAssistantPanel } from "@/components/scan-assistant/ScanAssistantPanel";
import { ScanReportAiRecommendations } from "@/components/scan-report/ScanReportAiRecommendations";
import { ScanReportAiSummary } from "@/components/scan-report/ScanReportAiSummary";
import { ScanReportDomainReputation } from "@/components/scan-report/ScanReportDomainReputation";
import { ScanReportFileIntelligencePanel } from "@/components/scan-report/ScanReportFileIntelligence";
import { ScanReportDownloads } from "@/components/scan-report/ScanReportDownloads";
import { ScanReportFiles } from "@/components/scan-report/ScanReportFiles";
import { ScanReportPerformancePanel } from "@/components/scan-report/ScanReportPerformance";
import { ScanReportSkeleton } from "@/components/scan-report/ScanReportSkeleton";
import { ScanReportStatusHero } from "@/components/scan-report/ScanReportStatusHero";
import { ScanReportThreats } from "@/components/scan-report/ScanReportThreats";
import { ScanReportTimeline } from "@/components/scan-report/ScanReportTimeline";
import { MonitorButton } from "@/components/monitors/MonitorButton";
import { MotionSection } from "@/components/dashboard/dashboard-motion";
import { CollapsibleSection } from "@/components/ui/CollapsibleSection";
import { fetchUsageSummary } from "@/lib/plan/client";
import type { ScanReport } from "@/lib/scan-report/types";

interface ScanReportShellProps {
  report: ScanReport;
  isDemo?: boolean;
}

export function ScanReportShell({ report, isDemo = false }: ScanReportShellProps) {
  const [premiumUnlocked, setPremiumUnlocked] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    void (async () => {
      const summary = await fetchUsageSummary();
      if (!cancelled) {
        setPremiumUnlocked(Boolean(summary?.allowPremiumAi));
        setLoading(false);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, []);

  if (loading) {
    return <ScanReportSkeleton />;
  }

  return (
    <div className="scan-report-print mx-auto max-w-4xl space-y-12 pb-8 lg:space-y-16">
      <nav className="print:hidden">
        <Link
          href="/scan-history"
          className="inline-flex items-center gap-2 rounded-lg px-2 py-1 text-sm font-medium text-scanonix-muted transition-colors hover:text-scanonix-orange focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-scanonix-orange/50"
        >
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2} aria-hidden="true">
            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
          </svg>
          Back to history
        </Link>
      </nav>

      <MotionSection>
        <ScanReportStatusHero report={report} />
      </MotionSection>

      {report.targetType === "website" ? (
        <MotionSection delay={0.04}>
          <div className="print:hidden">
            <MonitorButton targetUrl={report.target} isDemo={isDemo} />
          </div>
        </MotionSection>
      ) : null}

      <MotionSection delay={0.06}>
        <ScanReportAiRecommendations findings={report.findings} />
      </MotionSection>

      <MotionSection delay={0.08}>
        <ScanReportThreats findings={report.findings} />
      </MotionSection>

      <MotionSection delay={0.1}>
        <CollapsibleSection
          title="Advanced details"
          description="Domain reputation, scan timeline, files, performance, and exports"
          defaultOpen={false}
        >
          {report.aiAnalysis ? (
            <ScanReportAiSummary analysis={report.aiAnalysis} />
          ) : null}
          {report.intelligence?.domainReputation ? (
            <ScanReportDomainReputation reputation={report.intelligence.domainReputation} />
          ) : null}
          {report.fileIntelligence ? (
            <ScanReportFileIntelligencePanel intelligence={report.fileIntelligence} />
          ) : null}
          <ScanReportTimeline stages={report.timeline} />
          <ScanReportFiles files={report.files} />
          <ScanReportPerformancePanel performance={report.performance} />
          <ScanReportDownloads report={report} premiumUnlocked={premiumUnlocked} />
        </CollapsibleSection>
      </MotionSection>

      <motion.p
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.15 }}
        className="print:hidden text-center text-xs text-scanonix-muted/80"
      >
        Report ID {report.id} · Generated by Scanonix
      </motion.p>

      <ScanAssistantPanel report={report} isDemo={isDemo} />
    </div>
  );
}
