export {
  MAX_WATERMARK_PDF_BYTES,
  MAX_WATERMARK_PDF_PAGES,
  MAX_WATERMARK_TEXT_LENGTH,
  MIN_WATERMARK_FONT_SIZE,
  MAX_WATERMARK_FONT_SIZE,
  DEFAULT_WATERMARK_FONT_SIZE,
  WATERMARK_MARGIN_SMALL,
  WATERMARK_MARGIN_MEDIUM,
  WATERMARK_MARGIN_LARGE,
  DEFAULT_WATERMARK_MARGIN,
  MIN_WATERMARK_MARGIN,
  MAX_WATERMARK_MARGIN,
  DEFAULT_WATERMARK_COLOR,
  DEFAULT_WATERMARK_OPACITY,
  MIN_WATERMARK_OPACITY,
  MAX_WATERMARK_OPACITY,
  MIN_WATERMARK_ROTATION,
  MAX_WATERMARK_ROTATION,
  DEFAULT_CENTER_DIAGONAL_ROTATION,
  MAX_WATERMARK_IMAGE_BYTES,
  MAX_WATERMARK_IMAGE_LONG_EDGE,
  MIN_RELATIVE_WIDTH_RATIO,
  MAX_RELATIVE_WIDTH_RATIO,
  DEFAULT_RELATIVE_WIDTH_RATIO,
} from "./limits";

export {
  watermarkPdfDocument,
  createDefaultTextWatermarkOptions,
  createDefaultImageWatermarkOptions,
} from "./watermark-pdf";

export { buildWatermarkedPdfFilename } from "./filename";

export {
  loadWatermarkDocumentState,
  type LoadWatermarkDocumentOptions,
} from "./load-document";

export {
  resolvePageSelection,
  resolvePageSelectionToZeroBased,
  buildAllPagesList,
  parsePageRangeInputToFlatPages,
  toZeroBasedIndices,
} from "./page-range";

export {
  computeImageDrawSize,
  computeImageWatermarkAnchor,
  computeRotatedImageExtents,
  computeTextWatermarkAnchor,
  computeWatermarkDrawRotation,
  createWatermarkPageGeometry,
  localAnchorToNormalized,
  localAnchorToPdfDrawOptions,
  validateImageFitsInVisibleBox,
  validateTextFitsInVisibleBox,
  visibleLocalPointToPdf,
  type CropPageGeometry,
  type WatermarkLocalAnchor,
  type WatermarkPdfDrawOptions,
} from "./geometry";

export {
  containsUnsupportedWinAnsiCharacters,
  findUnsupportedWinAnsiCharacters,
  validateHexColor,
  validateOpacity,
  validateRotationDegrees,
  validateFontSize,
  validateMargin,
  validateRelativeWidthRatio,
  validateWatermarkText,
  validateTextWatermarkOptions,
  validateImageWatermarkOptions,
  validateWatermarkPdfOptions,
  validateImageDimensions,
  isAcceptedWatermarkPdfFile,
  assertAcceptedWatermarkPdfFile,
  ACCEPTED_WATERMARK_IMAGE_ACCEPT,
  isAcceptedWatermarkImageFile,
  getWatermarkImageFileError,
  canUseBoldFont,
  type ParsedHexColor,
} from "./validation";

export { detectExistingDigitalSignatures } from "./detect-signatures";

export {
  WatermarkPdfError,
  WATERMARK_PDF_PRIVACY_COPY,
  DIGITAL_SIGNATURE_WATERMARK_WARNING,
  getWatermarkPdfErrorMessage,
  type ImageWatermarkOptions,
  type TextWatermarkOptions,
  type ValidatedImageWatermarkOptions,
  type ValidatedTextWatermarkOptions,
  type ValidatedWatermarkPdfOptions,
  type WatermarkDocumentState,
  type WatermarkPageEntry,
  type WatermarkPageRotation,
  type WatermarkPdfErrorCode,
  type WatermarkPdfExportResult,
  type WatermarkPdfOptions,
  type WatermarkPosition,
  type WatermarkType,
} from "./types";

export {
  CROP_PREVIEW_JPEG_QUALITY,
  clampCropPreviewDevicePixelRatio,
  computeCropPreviewContainerWidth,
  computeCropPreviewRenderPlan,
  computeImagePreviewDimensions,
  computeImagePreviewOverlayStyle,
  computeTextPreviewOverlayNormalized,
  computeTextPreviewOverlayStyle,
  createPreviewGeometry,
  isBottomWatermarkPosition,
  isTopWatermarkPosition,
  measurePreviewTextWidth,
  type ComputeImagePreviewOverlayStyleArgs,
  type ComputeTextPreviewOverlayStyleArgs,
  type ImagePreviewOverlayStyle,
  type PreviewOverlayNormalizedResult,
  type TextPreviewOverlayStyle,
} from "./preview-ui";

export {
  WATERMARK_PREVIEW_CONTAINER_WIDTH_EPSILON,
  WatermarkPreviewRenderTracker,
  computeWatermarkPreviewDisplaySize,
  getWatermarkPreviewPdfRenderKey,
  resolveWatermarkPreviewContainerWidth,
  shouldUpdateWatermarkPreviewContainerWidth,
  type WatermarkPreviewDisplaySize,
  type WatermarkPreviewOverlayState,
  type WatermarkPreviewPdfRenderDeps,
} from "./preview-render";

export {
  DIGITAL_SIGNATURE_WATERMARK_WARNING as WATERMARK_DIGITAL_SIGNATURE_WARNING,
  MARGIN_PRESET_OPTIONS,
  MAX_OPACITY_PERCENT,
  MAX_RELATIVE_WIDTH_PERCENT,
  MIN_OPACITY_PERCENT,
  MIN_RELATIVE_WIDTH_PERCENT,
  POSITION_GRID,
  ROTATION_PRESET_OPTIONS,
  WATERMARK_POSITIONS,
  WATERMARK_PREVIEW_MAX_CSS_WIDTH,
  WATERMARK_PREVIEW_MIN_CSS_WIDTH,
  computeWatermarkEditorContainerWidth,
  WATERMARK_SECURITY_COPY,
  WATERMARK_UI_PRIVACY_COPY,
  buildImageWatermarkExportOptions,
  buildTextWatermarkExportOptions,
  buildWatermarkExportOptions,
  canExportWatermarkWorkspace,
  canUseBoldInWorkspace,
  clampFontSize,
  createDefaultWorkspaceSettings,
  exportWatermarkedPdf,
  getPositionLabel,
  getTextValidationError,
  getUnsupportedCharacterError,
  isTransparentPng,
  mapEngineErrorToMessage,
  opacityEngineToPercent,
  opacityPercentToEngine,
  relativeWidthPercentToRatio,
  relativeWidthRatioToPercent,
  resetWorkspaceSettings,
  resolvePreviewWatermark,
  sanitizeUserFacingError,
  switchWatermarkMode,
  validateRotationInput,
  validateWorkspaceColor,
  type ImageWorkspaceAsset,
  type MarginPresetValue,
  type PreviewWatermarkResult,
  type WatermarkWorkspaceSettings,
} from "./workspace-ui";
